netflixapp/urls.py
from django.urls import path
from . import views
from .views import Home, ProfileCreate, ProfileList, MovieList, MovieDetail, PlayMovie


app_name = 'netflixapp'

urlpatterns = [
    path('', Home.as_view(), name='Home'),  #WE USE THIS FORMAT COS OF OUR CLASS BASED VIEW
    path('profiles/', ProfileList.as_view(), name='profilelist'),
    path('profiles/create/', ProfileCreate.as_view(), name='profilecreate'),
    path('watch/<str:profile_id>/', MovieList.as_view(), name='movielist'), #WATCH/THE PROFILE(PROFILE_ID) UUID WHICH IS THE URL
    path('watch/detail/<str:movie_id>/', MovieDetail.as_view(), name='moviedetail'),
    path('watch/play/<str:movie_id>/', PlayMovie.as_view(), name='playmovie'),
]

netflixprj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings        #THE NECSSARY IMPORTS FOR MEDIA FILE LOCATING BELOW
from django.conf.urls.static import static   #THE NECSSARY IMPORTS FOR MEDIA FILE LOCATING BELOW

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('netflixapp.urls')),
    path('accounts/', include('allauth.urls')), #THIS PARTICULAR ONE IS NECESSARY FOR ALLAUTH AUTHENTICATION   
                                                #ENSURE YOU "PIP INSTALL DJANGO-ALLAUTH"
]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)   #TO LOCATE OUR MEDIA FILES WHICH ARE UPLOADED THROUGH DB
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    #TO BE PASS IN OUR HTML TEMPLATE TO BE DISPLAYED IN FRONTEND

netflixapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid
from datetime import datetime

# Create your models here.

CATEGORIES = (
    ('General','General'),      #others and kids category
    ('Kids', 'Kids'),
)

MOVIE_SELECTION =(
    ('seasonal', 'Seasonal'),
    ('single', 'Single'),
)



class CustomUser(AbstractUser):    #To make a user our own way 
    profiles = models.ManyToManyField('Profile', blank=True)  #for one to have access to many profiles(e.g parents for kids.(PG))


class Profile(models.Model): #AND NOW FOR THAT PROFILE ABOVE
    name = models.CharField(max_length = 200)
    age_limit = models.CharField(choices=CATEGORIES, max_length= 15)  #TOMAKE MANDATORY FOR USER TO CHOOSE AGE CATEGORY
    uuid = models.UUIDField(default=uuid.uuid4)   #TO KEEP TRACK OF INDIVIDUALS PROFILE WITH A UNIQUE ID

    def __str__(self):      #DUNDER METHOD TO RETURN NAME OF OUR PROFILE NAME IN THE DATABASE
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length = 200)
    description = models.TextField(blank=True, null=True)  #MIGHT NOT HAVE DESCRIPTION SO IN SUCH S CASE IT SEES BLANK
    created = models.DateTimeField(auto_now_add=True)      #CREATED TIME OF THE MOVIE
    uuid = models.UUIDField(default=uuid.uuid4)   #KEEP TRACK OF MOVIE WITH AUNIQUE ID
    genre = models.CharField(choices=MOVIE_SELECTION, max_length= 15)   #LIKE THE TYPE EITHER SEASONAL OR SINGLE
    video = models.ManyToManyField('Video')    #A MOVIE MIGHT BE SINGLE WITH MANY EPISODES SO MANY2MANY IS REQUIRED
    image = models.ImageField(upload_to ='covers')
    age_limit = models.CharField(choices=CATEGORIES, max_length = 10)

    def __str__(self):      #DUNDER METHOD TO RETURN NAME OF OUR TITLE IN THE DATABASE
        return self.title


class Video(models.Model):
    title = models.CharField(max_length = 200)
    file = models.FileField(upload_to='movies')

    def __str__(self):      #DUNDER METHOD TO RETURN TITLE OF VIDEO IN THE DATABASE
        return self.title

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Netflix</title>
    <link href="{% static "css/style.css/" %}" rel="stylesheet" />

    <script src="https://unpkg.com/ionicons@5.4.0/dist/ionicons.js"></script>
  </head>
  <body class="bg-black text-gray-100">
    <nav class="flex justify-between items-center py-3 px-4 fixed w-full z-50">
      <div class="w-6/12">
        <img
          src="{% static 'img/netflix.png' %}"
          alt="logo"
          class="w-5/12 md:w-2/12"
        />
      </div>

      <div>
        {% if request.user.is_authenticated %}
        <!--=== if user is logged in show logout ===-->
        <a
          href="{% url 'account_logout' %}"
          class="bg-primary_red py-1 px-3 text-white md:text-lg rounded-md"
        >
          Log Out
        </a>
        {% else %}

        <!--=== if user isnt logged in, show login ==-->
        <a
          href="{% url 'account_login' %}"
          class="bg-primary_red py-1 px-3 text-white md:text-lg rounded-md"
        >
          Sign In
        </a>
        {% endif %}
      </div>
    </nav>
    {% block content %}
    <!--===== INDEX TEMPLATE =====-->
    {% endblock content %}
    <footer class="px-5 py-10">
      <ul class="flex justify-between items-center">
        <li>&copy; All Right Reserved | 2022</li>
        <li>Netflix Clone</li>
        <li>Edited: Dikachi</li>
      </ul>
    </footer>
  </body>
</html>

templates/createprofile.html
{% extends 'base.html' %} {% load static %} {% block content %}
<section
  class="bg-primary_black min-h-screen py-20 md:py-32 flex-col flex items-center"
  style="background-image: url('{% static 'img/netflixbg.jpg' %}')"
>
  <div class="flex flex-wrap justify-center w-10/12 md:w-6/12">
    <form class="w-full md:w-8/12 bg-gray-900 p-5 rounded-lg" method="POST">
      {% csrf_token %}
      <h1 class="text-4xl text-center text-gray-100 font-medium">
        Create A Profile
      </h1>
      <div class="my-4">
        <label class="text-lg text-gray-200 font-medium mb-3">
          Profile Name
        </label>
        <input
          required
          class="p-2 bg-gray-500 rounded-sm text-gray-200 outline-none block w-full"
          type="text"
          name="name"
          id="id_name"
          placeholder="Profile name"
        />
      </div>
      <div class="my-4">
        <label class="text-lg text-gray-200 font-medium mb-3">
          Maturity Level
        </label>
        <select
          class="p-2 bg-gray-500 rounded-sm text-gray-200 outline-none block w-full"
          name="age_limit"
          id="id_age_limit"
        >
          <option value="All">All</option>
          <option value="Kids">Kids</option>
        </select>
      </div>
      <div class="flex justify-center items-center">
        <button
          class="px-4 py-2 rounded-md outline-none bg-primary_red text-gray-100"
          type="submit"
        >
          Create Profile
        </button>
      </div>
    </form>
  </div>
</section>
{% endblock content %}

templates/index.html
{% extends 'base.html' %} {% load static %} {% block content %}
<header
  class="min-h-screen bg-black bg-opacity-75 showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"
  style="background-image: url('{% static 'img/mainnetflixbg.jpg' %}')"
>
  <div
    class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col"
  >
    <h1 class="font-semibold text-4xl md:text-5xl w-10/12 md:w-3/4 text-center">
      Unlimited movies, TV shows, and more.
    </h1>
    <h3 class="text-xl md:text-xl py-5">Watch anywhere. Cancel anytime.</h3>
    <h4 class="text-sm md:text-lg pb-3">
      Ready to watch? Enter your email to create or restart your membership.
    </h4>

    <div class="w-full flex justify-center">
      <div class="flex justify-center items-center w-11/12 md:w-10/12">
        <input
          type="email"
          name=""
          id=""
          placeholder="Email address"
          class="md:py-5 py-4 px-2 placeholder-gray-500 rounded-tl-sm rounded-bl-sm outline-none text-gray-900 bg-gray-50 block w-8/12 md:w-3/4"
        />
        <button
          class="bg-primary_red font-medium md:font-normal md:w-1/4 flex justify-center items-center py-4 px-1 md:px-0 rounded-br-sm rounded-tr-sm md:text-2xl"
        >
          <span> Get Started </span>
          <ion-icon name="chevron-forward-outline" class="text-2xl"></ion-icon>
        </button>
      </div>
    </div>
  </div>
</header>

<section
  class="flex flex-col md:flex-row items-center border-gray-900 border-b-8"
  style="min-height: 70vh"
>
  <div
    class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10"
  >
    <h2 class="md:text-5xl text-4xl font-semibold mb-4">Enjoy on your TV.</h2>
    <h5 class="md:text-xl text-lg">
      Watch on Smart TVs, Playstation, Xbox, Chromecast, Apple TV, Blu-ray
      players, and more.
    </h5>
  </div>
  <div class="md:w-1/2 flex justify-center items-center">
    <img src="{% static 'img/netflixtv.png'%}" class="w-8/12" alt="" />
  </div>
</section>

<section
  class="flex flex-col md:flex-row items-center border-gray-900 border-b-8"
  style="min-height: 70vh"
>
  <div class="md:w-1/2 flex justify-center items-center order-2">
    <img src="{% static 'img/netflixmobile.jpg'%}" class="w-8/12" alt="" />
  </div>

  <div
    class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10"
  >
    <h2 class="md:text-5xl text-4xl font-semibold mb-4">
      Download your shows to watch offline.
    </h2>
    <h5 class="md:text-xl text-lg">
      Save your favorites easily and always have something to watch.
    </h5>
  </div>
</section>

<section
  class="flex flex-col md:flex-row items-center border-gray-900 border-b-8"
  style="min-height: 70vh"
>
  <div
    class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10"
  >
    <h2 class="md:text-5xl text-4xl font-semibold mb-4">
      Create profiles for kids.
    </h2>
    <h5 class="md:text-xl text-lg">
      Send kids on adventures with their favorite characters in a space made
      just for them—free with your membership.
    </h5>
  </div>
  <div class="md:w-1/2 flex justify-center items-center">
    <img src="{% static 'img/netflixkids.png'%}" class="w-8/12" alt="" />
  </div>
</section>
{% endblock content %}

templates/moviedetail.html
{% extends 'base.html' %} {% load static %} {% block content %}
<main class="bg-primary_black min-h-screen w-full">
  <section
    class="h-screen relative bg-no-repeat pb-8 pl-6 flex justify-end items-end bg-cover"
    style="background-image: url('{{ movie.image.url }}')"
  >
    <div>
      <h2
        class="text-6xl font-semibold text-white my-4"
        style="font-weight: bolder"
      >
        {{ movie.title }}
      </h2>
      <p class="w-11/12 md:w-5/12 font-medium text-white my-4">
        {{ movie.description }} {% lorem 1 %}
        <!--== IS TO MAKE IT ALIGN LEFT==-->
      </p>
      <div class="flex my-4">
        <a href="{% url 'netflixapp:playmovie' movie_id=movie.uuid %}">
          <button class="flex items-center bg-white py-2 px-5 rounded-md">
            <ion-icon name="play" class="text-2xl"></ion-icon>
            <span class="ml-3 font-medium"> Play </span>
          </button>
        </a>
      </div>
    </div>
  </section>
  <section class="bg-primary_black min-h-screen flex justify-center py-10">
    <div class="p-8 w-10/12 relative">
      <h2 class="text-gray-200 text-3xl font-medium">Description</h2>
      <div class="flex justify-center items-center min-w-full movie_lis">
        <p class="text-gray-100 text-lg">{{ movie.description }}</p>
      </div>
    </div>
  </section>
</main>
<script>
  const nav = document.querySelector("nav");

  document.addEventListener("scroll", (e) => {
    if (scrollY > 200) {
      nav.classList.add("bg-gray-900");
    } else {
      nav.classList.remove("bg-gray-900");
    }
  });
</script>
{% endblock content %}

templates/movielist.html
{% extends 'base.html' %} {% load static %} {% block content %}
<main class="bg-primary_black min-h-screen w-full">
  <section
    class="h-screen relative bg-no-repeat pb-8 pl-6 flex justify-end items-end bg-cover"
    style="background-image: url('{% static 'img/metime.jpg' %}')"
  >
    <div>
      <h2 class="text-6xl font-semibold text-black my-4">Me time</h2>
      <p class="w-11/12 md:w-5/12 font-medium text-white my-4">
        Me Time is a 2022 American buddy comedy film written and directed by
        John Hamburg. The film stars Kevin Hart, Mark Wahlberg, Regina Hall,
        Luis Gerardo
      </p>
      <div class="flex my-4">
        <button class="flex items-center bg-white py-2 px-5 rounded-md">
          <ion-icon name="play" class="text-2xl"></ion-icon>
          <span class="ml-3 font-medium"> Play </span>
        </button>

        <button
          class="ml-4 text-white flex items-center bg-gray-500 bg-opacity-80 py-2 px-5 rounded-md"
        >
          <ion-icon
            name="information-circle-outline"
            class="text-2xl"
          ></ion-icon>
          <span class="ml-3 font-medium"> More Info </span>
        </button>
      </div>
    </div>
  </section>
  <section class="bg-primary_black min-h-screen flex justify-center py-10">
    <div class="p-8 w-10/12 relative">
      <h2 class="text-gray-200 text-2xl font-medium">Popular on Netflix</h2>
      <div class="flex justify-center items-center min-w-full movie_lis">
        {% for movie in movies %}
        <a href="{% url 'netflixapp:moviedetail' movie_id=movie.uuid %}">
          <!--== TO MAKE THE MOVIE CLICKABLE TO VIEW THE MOVIE DETAIL ==-->
          <div
            class="h-40 m-4 bg-blue-500 flex-shrink-0 rounded-md cursor-pointer w-40"
          >
            <img src="{{movie.image.url}}" class="w-full h-full" alt="" />
          </div>
        </a>
        {% endfor %}
      </div>
    </div>
  </section>
</main>
{% endblock content %}

templates/profilelist.html
{% extends 'base.html' %} {% load static %} {% block content %}
<section
  class="bg-primary_black min-h-screen py-20 md:py-0 flex-col flex justify-center items-center"
  style="background-image: url('assets/background_netflix.jpg')"
>
  <h2 class="text-center font-medium text-5xl my-4 text-gray-100">
    Who's watching ?
  </h2>

  <div class="flex flex-wrap justify-center items-center w-10/12 md:w-6/12">
    {% for profile in profiles %}
    <a href="{% url 'netflixapp:movielist' profile_id=profile.uuid %}">
      <!--== TO DISPLAY MOVIE FOR UUID THAT EQUATES THE PROFILE_ID OF A USER ==-->
      <div
        class="w-32 h-32 m-4 bg-blue-500 rounded-md cursor-pointer justify-center items-center flex-col flex"
      >
        <p class="text-6xl" style="font-weight: 900">
          <!--== TO ENLARGE FONT IN OUR PROFILES ==-->
          {{ profile.name|slice:":1"}}
          <!--== TO TAKE ONLY THE FIRST LETTER TO DISPLAY ==-->
        </p>
        <p>{{ profile.name }}</p>
        <!--== TO PASS THE NAME ACCESSED FROM MODELS ==-->
      </div>
    </a>
    {% endfor %}
  </div>
  <div class="flex justify-center items-center">
    <a href="{% url 'netflixapp:profilecreate' %}">
      <button
        class="px-4 py-2 rounded-md outline-none bg-gray-400 text-gray-100"
        type="submit"
      >
        Add A New Profile
      </button>
    </a>
  </div>
</section>
{% endblock %}

templates/showmovie.html
{% extends 'base.html' %} {% load static %} {% block content %}
<main class="bg-primary_black h-full w-full">
  {{movie|json_script:'movie_data'}}
  <!--== WE ARE PASSING THE MOVIE PIPE JSON SCRIPT TO THE MOVIE_DATA ==-->
  <video src="assets/test.mp4" controls class="w-full h-screen player"></video>
</main>
<script>
  /* WE PASS THE JS CODE FOR FUNCTIONALITY */
  const videoEl = document.querySelector("video");
  const movie_data = JSON.parse(
    document.getElementById("movie_data").textContent
  );
  const url = new URL(location.href);
  const video_param = parseInt(url.searchParams.get("epi"))
    ? parseInt(url.searchParams.get("epi"))
    : 0;
  videoEl.setAttribute(
    "src",
    "http://localhost:8000/media/${movie_data[video_param].file}" /* WHEN DEPLOYING WE CHANGE URL TO THE NEW SITE URL NAME */
  );
</script>
{% endblock content %}